In [2]:
import numpy as np

A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

A_inverse = np.linalg.inv(A)

product_a = np.dot(A, A_inverse)
product_b = np.dot(A_inverse, A)

print("Matrix A:")
print(A)
print("\nInverse of A (A_inverse):")
print(A_inverse)
print("\nProduct A * A_inverse (Should be identity):")
print(product_a)
print("\nProduct A_inverse * A (Should be identity):")
print(product_b)


Matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of A (A_inverse):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Product A * A_inverse (Should be identity):
[[ 1.00000000e+00 -1.77635684e-15 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Product A_inverse * A (Should be identity):
[[ 1.00000000e+00 -8.88178420e-15 -1.42108547e-14]
 [ 1.77635684e-15  1.00000000e+00  0.00000000e+00]
 [-4.44089210e-16 -8.88178420e-16  1.00000000e+00]]
